version: '3.1'

volumes:
  prometheus_data: {}
  grafana_data: {}
  elasticsearch_data: {}

networks:
  monitoring:
    driver: bridge

services:

  springboot:  
    build:
      context: ./spring-boot    
    image: springboot-micrometer
    volumes:
      - ./elastic/kibana/kibana.yml/:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 8090:8080    
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - monitoring

  frontend:    
    build:
      context: ./frontend
    depends_on:
      - springboot
    image: frontend-micrometer
    ports:
      - 8091:8080
    networks:
      - monitoring
