version: '3.1'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitoring:
    driver: bridge

services:

  springboot:
    volumes:
      - ./spring-boot/build/libs/spring-boot-micrometer-1.jar:/usr/src/micrometer/spring-boot-micrometer-1.jar
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    image: springboot-micrometer
    ports:
      - 8090:8080
    command: "java -jar spring-boot-micrometer-1.jar"
    networks:
      - monitoring
    restart: always

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/prometheus_config:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - springboot
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./prometheus/grafana_config/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./prometheus/grafana_config/config.monitoring
    networks:
      - monitoring
    restart: always
