version: '3.1'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitoring:

services:

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus_config:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_config/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana_config/config.monitoring
    networks:
      - monitoring
    restart: always
