spring.application.name: springboot-micrometer-sample

management:
  metrics.tags.application: ${spring.application.name}
  endpoints:
    enabled-by-default: true
    web.exposure.include: '*'

endpoints:
  prometheus.sensitive: false

