spring:
  profiles:
    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    assaults:
      latencyActive: true
      latencyRangeStart: 1000
      latencyRangeEnd: 4500
      level: 1
    watcher:
      component: false
      restController: true
      service: false
      repository: false

management:
  metrics:
    export:
      chaosmonkey:
        enabled: true
    endpoint:
      chaosmonkey:
        enabled: true
      chaosmonkeyjmx:
        enabled: true