spring.application.name: springboot-micrometer-sample

logging:
  level:
    io.micrometer: DEBUG

management:
  metrics:
    tags.application: ${spring.application.name}
    export.elastic.enabled: false
    tags.region: "hamburg"
    tags.environment: "local"
    tags.subdomain: "apartment"
    tags.programming_language: "java"
  endpoints:
    enabled-by-default: true
    web.exposure.include: '*'

endpoints:
  prometheus.sensitive: false

