spring:
  profiles:
    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    assaults:
      latencyActive: true
      #latencyRangeStart: 100
      latencyRangeEnd: 2000
      exceptionsActive: false
      killApplicationActive: false
      level: 3
    watcher:
      component: false
      restController: true
      service: false
      repository: false

management:
  metrics:
    export:
      chaosmonkey:
        enabled: true
    endpoint:
      chaosmonkey:
        enabled: true
      chaosmonkeyjmx:
        enabled: true