management:
  metrics:
    export:
      elastic:
        enabled: true
        host: http://elasticsearch:9300
        index: micrometer-metrics
        step: 5s
    tags.environment: docker_on_markus_mac