management:
  metrics:
    export:
      elastic:
        enabled: true
        host: "http://elasticsearch:9200"
        index: "micrometer-metrics"
        step: 5s
        batch-size: 5
    tags.environment: "docker_on_markus_mac"